options:
    formatter: stylish

files:
    include: 'src/**/*.sass'

rules:
    attribute-quotes: 2
    bem-depth: 2
    border-zero:
        - 2
        - convention: none
    brace-style:
        - 2
        - allow-single-line: false
    class-name-format:
        - 2
        - allow-leading-underscore: false
          convention: hyphenatedbem
    clean-import-paths: 2
    declarations-before-nesting: 2
    empty-args: 2
    empty-line-between-blocks:
        - 2
        - allow-single-line-rulesets: false
    extends-before-declarations: 2
    extends-before-mixins: 2
    final-newline: 2
    force-attribute-nesting: 0
    force-element-nesting: 2
    force-pseudo-nesting: 0
    function-name-format:
        - 2
        - allow-leading-underscore: false
          convention: hyphenatedbem
    hex-length: 2
    hex-notation: 2
    id-name-format:
        - 2
        - allow-leading-underscore: false
          convention: hyphenatedlowercase
    indentation:
        - 2
        - size: 4
    leading-zero:
        - 2
        - include: true
    max-file-line-count: 2
    max-line-length:
        - 2
        - length: 120
    mixin-name-format:
        - 2
        - allow-leading-underscore: false
          convention: hyphenatedbem
    mixins-before-declarations: 2
    nesting-depth: 2
    no-attribute-selectors: 1
    no-color-hex: 0
    no-color-keywords: 2
    no-color-literals: 2
    no-combinators: 1
    no-css-comments: 0
    no-debug: 2
    no-disallowed-properties: 0
    no-duplicate-properties: 2
    no-empty-rulesets: 2
    no-extends: 0
    no-ids: 2
    no-important: 2
    no-invalid-hex: 2
    no-mergeable-selectors: 2
    no-misspelled-properties: 2
    no-qualifying-elements: 2
    no-trailing-whitespace: 2
    no-trailing-zero: 2
    no-transition-all: 2
    no-universal-selectors: 2
    no-url-domains: 2
    no-url-protocols: 2
    no-warn: 2
    one-declaration-per-line: 2
    placeholder-in-extend: 2
    placeholder-name-format:
        - 2
        - allow-leading-underscore: false
          convention: hyphenatedbem
    property-sort-order:
        - 2
        -   order:

            # Box

            - display
            - flex
            - flex-basis
            - flex-direction
            - flex-flow
            - flex-grow
            - flex-shrink
            - flex-wrap
            - align-content
            - align-items
            - align-self
            - justify-content
            - order

            - position
            - top
            - right
            - bottom
            - left
            - z-index

            - width
            - min-width
            - max-width

            - height
            - min-height
            - max-height

            - margin
            - margin-top
            - margin-right
            - margin-bottom
            - margin-left

            - padding
            - padding-top
            - padding-right
            - padding-bottom
            - padding-left

            - float
            - clear

            - columns
            - column-gap
            - column-fill
            - column-rule
            - column-span
            - column-count
            - column-width

            # Border

            - border
            - border-top
            - border-right
            - border-bottom
            - border-left
            - border-width
            - border-top-width
            - border-right-width
            - border-bottom-width
            - border-left-width

            - border-style
            - border-top-style
            - border-right-style
            - border-bottom-style
            - border-left-style

            - border-radius
            - border-top-left-radius
            - border-top-right-radius
            - border-bottom-left-radius
            - border-bottom-right-radius

            - border-color
            - border-top-color
            - border-right-color
            - border-bottom-color
            - border-left-color

            - outline
            - outline-color
            - outline-offset
            - outline-style
            - outline-width

            # Text

            - color

            - font
            - font-family
            - font-size
            - font-smoothing
            - font-style
            - font-variant
            - font-weight

            - letter-spacing
            - line-height
            - list-style

            - text-align
            - text-decoration
            - text-indent
            - text-overflow
            - text-rendering
            - text-shadow
            - text-transform
            - text-wrap

            - white-space
            - word-spacing

            # Background

            - background
            - background-attachment
            - background-clip
            - background-color
            - background-image
            - background-repeat
            - background-position
            - background-size

            # Transform

            - transform
            - transform-box
            - transform-origin
            - transform-style

            # Transition

            - transition
            - transition-delay
            - transition-duration
            - transition-property
            - transition-timing-function

            # Animation

            - animation
            - animation-name
            - animation-duration
            - animation-timing-function
            - animation-delay
            - animation-iteration-count
            - animation-direction
            - animation-fill-mode
            - animation-play-state

            # Other

            - border-collapse
            - border-spacing
            - box-shadow
            - caption-side
            - content
            - cursor
            - empty-cells
            - opacity
            - overflow
            - quotes
            - speak
            - table-layout
            - vertical-align
            - visibility

    property-units: 0
    pseudo-element: 2
    quotes: 2
    shorthand-values: 2
    single-line-per-selector: 2
    space-after-bang: 2
    space-after-colon: 2
    space-after-comma: 2
    space-around-operator: 2
    space-before-bang: 2
    space-before-brace: 2
    space-before-colon: 2
    space-between-parens: 2
    trailing-semicolon: 2
    url-quotes: 2
    variable-for-property: 0
    variable-name-format:
        - 2
        - allow-leading-underscore: false
          convention: hyphenatedbem
    zero-unit: 2
